
TRANSLATIONS = {
    'Acid_Jazz': 'Эйсид-джаз',
    'Afro_Cuban_Jazz': 'Афро-кубинский джаз',
    'Alternative_rock': 'Арт-рок',
    'Avant_garde_Jazz': 'Авангардный джаз',
    'Beat': 'Бит',
    'Bebop': 'Бибоп',
    'BlackMetal': 'Блэк-метал',
    'Bossanova': 'Босанова',
    'C_pop': 'C-pop',
    'CelticMetal': 'Кельтик-метал',
    'Chicago_Blues': 'Чикаго-блюз',
    'Chicago_Jazz': 'Чикагский джаз',
    'Christian_Rock': 'Христианский рок',
    'Cool_Jazz': 'Кул-джаз',
    'Country_Blues': 'Кантри-блюз',
    'Dance_pop': 'Данс-поп',
    'Dark_metal': 'Дарк-метал',
    'Death_metal': 'Дэт-метал',
    'Delta_Blues': 'Дельта-блюз',
    'Dixieland': 'Диксиленд',
    'Doom_metal': 'Дум-метал',
    'Electric_Blues': 'Электрик-блюз',
    'Electropop': 'Электропоп',
    'Europop': 'Европоп',
    'Experimental_Rock': 'Экспериментальный рок',
    'Folk_Rock': 'Фолк-рок',
    'Folk_metal': 'Фолк-метал',
    'Free_Jazz': 'Фри-джаз',
    'Garage_Rock': 'Гаражный рок',
    'Glam_Rock': 'Глэм-рок',
    'Glam_metal': 'Глэм-метал',
    'Gothic_Rock': 'Готик-рок',
    'Gothic_metal': 'Готик-метал',
    'Groove_metal': 'Грув-метал',
    'Grunge': 'Гранж',
    'Hard_Bop': 'Хард-боп',
    'Hard_Rock': 'Хард-рок',
    'Heartland_Rock': 'Хартленд-рок',
    'Heavy_metal': 'Хеви-метал',
    'Indie_Rock': 'Инди-рок',
    'Instrumental_Rock': 'Инструментальный рок',
    'J_pop': 'J-pop',
    'Jazz_Funk': 'Джаз-фанк',
    'Jazz_Fusion': 'Джаз-фьюжн',
    'Jazz_Manush': 'Джаз-мануш',
    'Jazz_Rap': 'Джаз-рэп',
    'K_pop': 'K-pop',
    'Latin_American_Jazz': 'Латиноамериканский джаз',
    'Mandopop': 'Mandopop',
    'Mashup': 'Мэшап',
    'Mat_metal': 'Мат-метал',
    'Math_rock': 'Математический рок',
    'Modal_Jazz': 'Модальный джаз',
    'Neoclassical_metal': 'Неоклассический метал',
    'New_Orleans_Jazz': 'Новоорлеанский джаз',
    'Noise_rock': 'Нойз-рок',
    'Nu_Jazz': 'Ню-джаз',
    'Operatic_pop': 'Operatic pop',
    'OrientalMetal': 'Ориентал-метал',
    'PaganMetal': 'Пейган-метал',
    'Post_metal': 'Пост-метал',
    'Post_punk': 'Пост-панк',
    'Postbop': 'Постбоп',
    'PowerMetal': 'Пауэр-метал',
    'Progressive_metal': 'Прогрессивный метал',
    'Proto_punk': 'Прото-панк',
    'Psychedelic_rock': 'Психоделический рок',
    'Pub_rock': 'Паб-рок',
    'Punk_Jazz': 'Панк-джаз',
    'Punk_rock': 'Панк-рок',
    'Q_pop': 'Q-pop',
    'Ska_Jazz': 'Ска-джаз',
    'SludgeMetal': 'Сладж-метал',
    'Smooth_jazz': 'Smooth jazz',
    'Soft_Rock': 'Софт-рок',
    'Sophisti_pop': 'Sophisti-pop',
    'Soul_Jazz': 'Соул-джаз',
    'Southern_Rock': 'Сатерн-рок',
    'Space_Rock': 'Спейс-рок',
    'Space_age_pop': 'Space age pop',
    'Speed_metal': 'Спид-метал',
    'StonerMetal': 'Стоунер-метал',
    'Stoner_Rock': 'Стоунер-рок',
    'Stride': 'Страйд',
    'Sunshine_pop': 'Sunshine pop',
    'Surf_Rock': 'Сёрф-рок',
    'Swing': 'Свинг',
    'Symphonic_metal': 'Симфоник-метал',
    'Texas_Blues': 'Техас-блюз',
    'Thrash_metal': 'Трэш-метал',
    'Tin_pop': 'Тин-поп',
    'Traditional_pop_music': 'Традиционная поп-музыка',
    'VanguardMetal': 'Авангард-метал',
    'Viking_metal': 'Викинг-метал',
    'bass_tool': 'Бас-гитара',
    'drums_tool': 'Ударные',
    'guitar_tool': 'Соло и ритм - гитара',
    'rythm_guitar_tool': 'Ритм-гитара',
    'solo_guitar_tool': 'Соло-гитара',
    'vocals_tool': 'Вокал'
}